import type { Case } from './case-types';

export const managers = ['Amira Patel', 'Daniel Hughes', 'Sophie Bennett', 'Marcus Reed'];
// Fictional training examples only; none of these statements describe real pupils.
export const initialCases: Case[] = [
  { id:'ST-2048', name:'Maya Thompson', year:'Year 9', form:'9H', manager:'Amira Patel', status:'Due Soon', stage:4, deadline:'Today, 15:30', concern:'Difficulty settling after a change in routine', context:'Maya left a science lesson after a timetable change. She returned to speak with staff after a short break.', voice:'“I did not know where I was meant to be, and everyone was looking at me.”', reporter:'Ms E. Foster · Science', reported:'Today, 09:12', decision:'Progress to intervention', rationale:'A predictable transition plan and a trusted check-in should reduce uncertainty before lessons.', actions:[{id:1,text:'Agree a quiet arrival routine for science',owner:'Ms E. Foster',due:'Tomorrow',done:true},{id:2,text:'Schedule morning check-in with Maya',owner:'Amira Patel',due:'Tomorrow',done:false},{id:3,text:'Share the lesson transition plan with home',owner:'Amira Patel',due:'Friday',done:false}], acknowledgements:{School:true,Student:false,Family:false}, checklist:{'Receiving teacher briefed':false,'First-day welcome arranged':false,'Check-in schedule agreed':false,'Student confirms readiness':false}, history:['Intervention plan drafted · Today, 11:20','Triage decision recorded · Today, 10:06','Reflective report submitted · Today, 09:12'] },
  { id:'ST-2047', name:'Leo Williams', year:'Year 8', form:'8C', manager:'Daniel Hughes', status:'Breached', stage:3, deadline:'Yesterday, 16:00', concern:'Repeated absence from afternoon registration', context:'Leo has missed two afternoon registrations this week; staff noted a recent change to his transport home.', voice:'“I worry I will miss my lift if I am late leaving.”', reporter:'Mr A. Shah · Form tutor', reported:'Yesterday, 08:45', decision:'Awaiting decision', rationale:'', actions:[], acknowledgements:{School:false,Student:false,Family:false}, checklist:{'Receiving teacher briefed':false,'First-day welcome arranged':false,'Check-in schedule agreed':false,'Student confirms readiness':false}, history:['SLA deadline passed · Yesterday, 16:00','Reflective report submitted · Yesterday, 08:45'] },
  { id:'ST-2045', name:'Aisha Rahman', year:'Year 10', form:'10B', manager:'Sophie Bennett', status:'On Track', stage:6, deadline:'Thu, 12:00', concern:'Supporting a confident return after time out', context:'Aisha is preparing to return to English following a short period of supported learning.', voice:'“I would like to know what I have missed before I go back.”', reporter:'Ms K. James · English', reported:'Monday, 14:26', decision:'Progress to intervention', rationale:'A paced return with a curriculum catch-up and named point of contact.', actions:[{id:1,text:'Prepare catch-up pack',owner:'Ms K. James',due:'Wednesday',done:true},{id:2,text:'Agree a first-lesson welcome',owner:'Sophie Bennett',due:'Thursday',done:true}], acknowledgements:{School:true,Student:true,Family:true}, checklist:{'Receiving teacher briefed':true,'First-day welcome arranged':true,'Check-in schedule agreed':false,'Student confirms readiness':false}, history:['Agreement acknowledged by all parties · Tuesday, 15:02','Intervention actions reviewed · Tuesday, 11:30','Reflective report submitted · Monday, 14:26'] },
  { id:'ST-2043', name:'Noah Clarke', year:'Year 7', form:'7F', manager:'Amira Patel', status:'On Track', stage:2, deadline:'Fri, 10:00', concern:'Peer disagreement during lunchtime', context:'A disagreement in the playground was de-escalated with staff support. Both pupils requested space.', voice:'“I want to sort it out, just not in front of everybody.”', reporter:'Mrs R. Lewis · Pastoral', reported:'Tuesday, 13:10', decision:'Awaiting decision', rationale:'', actions:[], acknowledgements:{School:false,Student:false,Family:false}, checklist:{'Receiving teacher briefed':false,'First-day welcome arranged':false,'Check-in schedule agreed':false,'Student confirms readiness':false}, history:['Reflective report submitted · Tuesday, 13:10'] },
  { id:'ST-2039', name:'Ella Morgan', year:'Year 11', form:'11D', manager:'Marcus Reed', status:'Due Soon', stage:5, deadline:'Tomorrow, 09:00', concern:'Agreed study support after missed coursework', context:'Ella has found recent coursework deadlines difficult alongside family commitments.', voice:'“It helps when the work is broken into smaller parts.”', reporter:'Mr J. Price · Design technology', reported:'Monday, 09:34', decision:'Progress to intervention', rationale:'A stepped coursework plan with brief weekly check-ins.', actions:[{id:1,text:'Break coursework into weekly milestones',owner:'Mr J. Price',due:'Tomorrow',done:false},{id:2,text:'Arrange weekly progress check-in',owner:'Marcus Reed',due:'Friday',done:false}], acknowledgements:{School:true,Student:true,Family:false}, checklist:{'Receiving teacher briefed':false,'First-day welcome arranged':false,'Check-in schedule agreed':false,'Student confirms readiness':false}, history:['Agreement shared for acknowledgement · Tuesday, 12:10','Intervention plan drafted · Monday, 15:20','Reflective report submitted · Monday, 09:34'] },
];